### PR TITLE
Spelling Fixes and other enhancements

### PR DESCRIPTION
**Pull request by ghost**
Changed guilds to server (In help), improved TOS, and converted the ban message from passive to active voice. Fixed extra space on specifying an amount in the gift command. Improved warning banner on transfer logging. Changed message on getting weekly bonus. Fixed missing period when going to a page number that does not exist. Fixed unnecessary comma on profile command help, added period on the work command in help. Removed requirement for owner to see channel id. Improved welcome message blank error, improved error message on Insufficient perms on the specified welcome channel, improved addowner command no user error, improved unbanwork blank error, improved the word already banned error, improved the unban word message, improved the blank ban word error, improved the error on Insufficient perms to kick members, improved error on avoiding kicking bots. Reomved dig and replaced with use. Fix the missing ! in Thanks for stopping by the shop. Yep, that's all.

### CODE REVIEW

**Comment by YumYummity** [comment]
Guilds to server is included in #24

**Comment by ghost** [comment]
> Guilds to server is included in #24

Yes, but your branch cannot be merged mine can.

**Comment by YumYummity** [comment]
that's because of merge conflicts, mine WAS mergeable before Beezo did a few updates. I still have to maintain it; mine is a mass rename to follow Guilded's actual response parameters. guilded.py only keeps `.guild` for discord.py compatibility so I've renamed every possible mention of guild to server. (excluding the API)

**Comment by ghost** [comment]
Rayz is shutting down, https://www.guilded.gg/Rayz/blog/box-drawings-heavy-quadruple-dash-vertical-announcements/Rayz-is-shutting-down-for-good

**Pull request closed without merging**
