### PR TITLE
Some spelling fixes + Better error management on ?sell, ?gift and ?give with no item/user.

### PR DESCRIPTION
**Pull request by DVT7125**
Title.

### CODE REVIEW

**Comment by DVT7125** [comment]
I just fixed the ambiguous error of nonetype when someone says {prefix}sell with no item.

**Comment by DVT7125** [comment]
> 
And now also with ?gift and ?give.

**Review by YumYummity — CHANGES_REQUESTED** [review]
an Item, an Amount instead of a Item, a Amount.

Nothing wrong with code as far as I can see.

**Review by Peyton2017 — COMMENTED** [review]
+1

**Pull request merged**
